# Generated by Django 6.0.6 on 2026-07-05 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('accueil', 'Accueil'), ('media', 'Média'), ('chorale', 'Chorale'), ('consistoire', 'Consistoire'), ('intercession', 'Intercession'), ('femme_famille', 'Services Femme et Famille'), ('cas_social', 'Commission Cas Social')], max_length=32, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rayon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64, unique=True)),
                ('quartier_reference', models.CharField(blank=True, max_length=255)),
                ('chef_rayon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rayons_diriges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrayerMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lieu', models.CharField(help_text='Adresse / nom du fidèle qui reçoit la réunion.', max_length=255)),
                ('statut', models.CharField(choices=[('prevue', 'Prévue'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée')], default='prevue', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('rayon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunions', to='core.rayon')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('rayon', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DepartmentMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_dans_departement', models.CharField(choices=[('membre', 'Membre'), ('responsable', 'Responsable')], default='membre', max_length=16)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres_dept', to='core.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'department')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences_enregistrees', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prayer_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='core.prayermeeting')),
            ],
            options={
                'unique_together': {('prayer_meeting', 'user')},
            },
        ),
    ]
